language: go
go:
  - "1.10"
  - master
before_install:
  - go get -u github.com/golang/dep/cmd/dep
install:
  - dep ensure
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)